# Generated by Django 5.0.6 on 2024-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_listing_price_listing_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
