# Generated by Django 5.0.6 on 2024-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_listing_price_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
